sudo: required
git:
  depth: false
services:
  - docker
env:
  global:
    - DOCKER_USERNAME=travis
jobs:
  include:
    - stage: 'Tests' # naming the Tests stage
      name: 'Unit Tests' # names the first Tests stage job
      language: elixir
      elixir:
        - 1.9
      otp_release:
        - 22.0
      cache:
        directories:
          - _build
          - deps
          - assets/node_modules
      services:
        - postgresql
      addons:
        postgresql: '9.6'
        apt:
          packages:
            - postgresql-9.6-postgis-2.4
      before_script:
        - psql -c 'create database nightingale_test;' -U postgres
      install:
        - gem install coveralls-multi
        - mix local.hex --force
        - mix local.rebar --force
        - mix deps.get
        - nvm install 12.4.0 && nvm use 12.4.0
        - npm install --prefix assets
      script:
        - MIX_ENV=test mix coveralls.json
        - npm test --prefix assets
        - bin/ci-coverage
    - stage: docker deploy
      name: 'Deploy'
      if: branch = master
      script: skip
      before_deploy:
        - echo $DOCKER_PASSWORD | docker login harbor.nightingale.revelry.org -u $DOCKER_USERNAME --password-stdin
        - export ROLLBAR_DEPLOY_ID=$(./bin/rollbar_release started)
      after_deploy:
        - ./bin/rollbar_release succeeded
      deploy:
        provider: script
        script: bin/docker_pub . library/nightingale harbor.nightingale.revelry.org
        on:
          branch: master
